### ISSUE TITLE
let the function return the vector(s) of pred corrected observations

### ISSUE THREAD

**Issue by smouksassi** [smouksassi/ComputePI#1]
When the user wants to overlay observed data on pred corrected vpc quantiles these obs should be pred corrected  currently the user has no access to this data and need to recompute by hand  maybe when pred correction is happening we add a list of pred corrected obs

**Comment by olivierbarriere** [comment]
Added a data.frame with DVC, PRED, MEDPRED to the output in case of predcorrection.

**Comment by smouksassi** [comment]
after giving it more thoughts, we should also provide the observations even when we are not pred correcting. Since we might be modifying the observed when we have lloq etc. whatever we might need to the plotting should be in this slot with or without pred correction. what is your opinion on that ? do we let the user keep track of what happens to the obs or we give it to him so it is ready for plotting?
